mqtt_example: mqtt_bacon_cape.c \
              led_ctrl.c \
              slider_ctrl.c \
              button_ctrl.c \
              eeprom_ctrl.c \
              display7seg_ctrl.c 
	gcc mqtt_bacon_cape.c led_ctrl.c slider_ctrl.c button_ctrl.c eeprom_ctrl.c display7seg_ctrl.c -o mqtt_bacon_cape -lpaho-mqtt3c -Wall
