mqtt_example: mqtt_bacon_cape.c \
              ../bacon_cape_lib/led_ctrl.c \
              ../bacon_cape_lib/slider_ctrl.c \
              ../bacon_cape_lib/button_ctrl.c \
              ../bacon_cape_lib/eeprom_ctrl.c \
              ../bacon_cape_lib/display7seg_ctrl.c 
	gcc mqtt_bacon_cape.c ../bacon_cape_lib/led_ctrl.c ../bacon_cape_lib/slider_ctrl.c ../bacon_cape_lib/button_ctrl.c ../bacon_cape_lib/eeprom_ctrl.c ../bacon_cape_lib/display7seg_ctrl.c -o mqtt_bacon_cape -lpaho-mqtt3c -Wall
