lib_validator: lib_validator.c \
               ../bacon_cape_lib/led_ctrl.c \
               ../bacon_cape_lib/slider_ctrl.c \
               ../bacon_cape_lib/button_ctrl.c \
               ../bacon_cape_lib/eeprom_ctrl.c \
               ../bacon_cape_lib/display7seg_ctrl.c \
               ../bacon_cape_lib/acc_ctrl.c \
               ../bacon_cape_lib/general_functions.c 
	gcc lib_validator.c ../bacon_cape_lib/led_ctrl.c ../bacon_cape_lib/slider_ctrl.c ../bacon_cape_lib/button_ctrl.c ../bacon_cape_lib/eeprom_ctrl.c ../bacon_cape_lib/display7seg_ctrl.c ../bacon_cape_lib/acc_ctrl.c ../bacon_cape_lib/general_functions.c -o lib_validator -Wall
