acc_test:      acc_test.c \
               ../bacon_cape_lib/led_ctrl.c \
               ../bacon_cape_lib/slider_ctrl.c \
               ../bacon_cape_lib/button_ctrl.c \
               ../bacon_cape_lib/eeprom_ctrl.c \
               ../bacon_cape_lib/display7seg_ctrl.c \
               ../bacon_cape_lib/accelerometer_ctrl.c \
               ../bacon_cape_lib/general_functions.c 
	gcc acc_test.c ../bacon_cape_lib/led_ctrl.c ../bacon_cape_lib/slider_ctrl.c ../bacon_cape_lib/button_ctrl.c ../bacon_cape_lib/eeprom_ctrl.c ../bacon_cape_lib/display7seg_ctrl.c ../bacon_cape_lib/accelerometer_ctrl.c ../bacon_cape_lib/general_functions.c -o acc_test -Wall